<a href="https://colab.research.google.com/github/falakj07/Data-Normalization-and-Data-Type-Conversion/blob/main/Data_Normalization_and_Data_Type_Conversion_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 14 - Data normalization and Data Type Conversion

## Name- Falak Jain
## PRN - 25070123047
## ENTC A3
## 01.04.2026

In [ ]:
# PART A - Data Normalization

In [4]:
## Dataset
import pandas as pd
import numpy as np

data = {
'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
'Price' : [55000,20000,30000,2000,8000,45000],
'Units sold' :[25,60,35,80,50,15],
'Discount':[10,15,20,12,18,8]
}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        20
3  Headphones   2000          80        12
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [6]:
# Min - Max Normaliztaion for price
df["Price_MinMax"] = (df["Price"] - df["Price"].min()) / (df["Price"].max() - df["Price"].min())

print("\nMinMax Normalised Price")
print(df[['Product', 'Price', 'Price_MinMax']])

MinMax Normalised Price
      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [12]:
#2. Z-Score Normalization for Price
df["Units_ZScore"] = (df["Units sold"] - df["Units sold"].mean()) / df["Units sold"].std()

print("\nZ-Score Normalized Units Sold")
print(df[['Product', 'Units sold', 'Units_ZScore']])

Z-Score Normalized Units Sold
      Product  Units sold  Units_ZScore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [8]:
# Normalize Multiple Columns
cols = ['Price','Units sold','Discount']


df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print("\nMin-Max Normalized DataFrame:")
print(df_norm)

Min-Max Normalized DataFrame:
      Price  Units sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  1.000000
3  0.000000    1.000000  0.333333
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
#

In [14]:
# 3 . Decimal scaling
df["Price_Scaled"] = df["Price"] / 100

print('\nDecimal Scaling')
print(df[['Product', 'Price', 'Price_Scaled']])

Decimal Scaling
      Product  Price  Price_Scaled
0      Laptop  55000         550.0
1      Mobile  20000         200.0
2      Tablet  30000         300.0
3  Headphones   2000          20.0
4  Smartwatch   8000          80.0
5      Camera  45000         450.0

In [ ]:
# Part B - Turning categorical variables into quantative variables in python

In [15]:
data = {
    'Order ID': [101, 102, 103, 104, 105, 106],
    'Customer_Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    "Payment_Method": ['Credit Card', 'PayPal', 'Credit Card', 'PayPal', 'Credit Card', 'PayPal'],
    'Product-category': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'City':['New York', 'Los Angeles', 'Chicago', 'San Francisco', 'Miami', 'Seattle'],
    'Order_value': [1500, 800, 2000, 1667, 12788, 7756]
}

df1=pd.DataFrame(data)
df1

,Order ID,Customer_Gender,Payment_Method,Product-category,City,Order_value
0,101,Male,Credit Card,Electronics,New York,1500
1,102,Female,PayPal,Clothing,Los Angeles,800
2,103,Male,Credit Card,Electronics,Chicago,2000
3,104,Female,PayPal,Clothing,San Francisco,1667
4,105,Male,Credit Card,Electronics,Miami,12788
5,106,Female,PayPal,Clothing,Seattle,7756

In [16]:
## Method1 : Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df1['Gender_Label'] = le.fit_transform(df1['Customer_Gender'])
df1

,Order ID,Customer_Gender,Payment_Method,Product-category,City,Order_value,Gender_Label
0,101,Male,Credit Card,Electronics,New York,1500,1
1,102,Female,PayPal,Clothing,Los Angeles,800,0
2,103,Male,Credit Card,Electronics,Chicago,2000,1
3,104,Female,PayPal,Clothing,San Francisco,1667,0
4,105,Male,Credit Card,Electronics,Miami,12788,1
5,106,Female,PayPal,Clothing,Seattle,7756,0

In [18]:
## Method2 : One - Hot encoding
df_encoded = pd.get_dummies(df1, columns=['Payment_Method'])

df_encoded

,Order ID,Customer_Gender,Product-category,City,Order_value,Gender_Label,Payment_Method_Credit Card,Payment_Method_PayPal
0,101,Male,Electronics,New York,1500,1,True,False
1,102,Female,Clothing,Los Angeles,800,0,False,True
2,103,Male,Electronics,Chicago,2000,1,True,False
3,104,Female,Clothing,San Francisco,1667,0,False,True
4,105,Male,Electronics,Miami,12788,1,True,False
5,106,Female,Clothing,Seattle,7756,0,False,True

In [19]:
#Method 3:Dummy Encoding
df_dummy = pd.get_dummies(df1, columns=['Payment_Method'], drop_first=True)
df_dummy

,Order ID,Customer_Gender,Product-category,City,Order_value,Gender_Label,Payment_Method_PayPal
0,101,Male,Electronics,New York,1500,1,False
1,102,Female,Clothing,Los Angeles,800,0,True
2,103,Male,Electronics,Chicago,2000,1,False
3,104,Female,Clothing,San Francisco,1667,0,True
4,105,Male,Electronics,Miami,12788,1,False
5,106,Female,Clothing,Seattle,7756,0,True

# New Dataset Operations

In [20]:
df  = pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [21]:
# Min Max Normalisation
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max()
- df['Price'].min())
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583
2,P103,USB Keyboard,699,4.1,870,180,0.016194
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069
4,P105,Smartwatch,3999,4.4,3050,520,0.149798
5,P106,Power Bank,1199,4.2,1750,390,0.036437
6,P107,Laptop Stand,899,4.0,620,140,0.024291
7,P108,Webcam,1899,4.3,1120,260,0.064777
8,P109,Portable SSD,5499,4.7,1850,330,0.210526
9,P110,Wireless Charger,999,4.2,760,190,0.028340
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632
13,P114,Tablet Stand,699,4.1,540,120,0.016194
14,P115,USB Hub,899,4.2,870,200,0.024291
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486
20,P121,Phone Holder,499,4.0,420,150,0.008097
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227
23,P124,Smart Plug,799,4.2,720,210,0.020243
24,P125,WiFi Router,3499,4.5,2100,390,0.129555
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089
26,P127,VR Headset,12999,4.7,3100,140,0.514170
27,P128,Microphone,2199,4.3,1300,270,0.076923
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583
30,P131,Action Camera,9999,4.6,2100,200,0.392713
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555
33,P134,Portable Projector,11999,4.6,1450,120,0.473684
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628
35,P136,Desk Organizer,599,4.1,450,160,0.012146
36,P137,USB Flash Drive,799,4.2,900,320,0.020243
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198
42,P143,Security Camera,4999,4.4,2100,260,0.190283
43,P144,Drone Camera,24999,4.7,1800,70,1.000000
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826
45,P146,Air Fryer,7999,4.6,2200,200,0.311741
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085
47,P148,Smart Scale,2499,4.4,980,170,0.089069
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555
49,P150,Portable Fan,999,4.2,760,240,0.028340

In [28]:
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max()
- df['Price'].max())
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Reviews_MinMax,Price_ZScore,Price_Scaled,Review_Scaled
0,P101,Wireless Mouse,799,4.3,1520,350,inf,-0.052887,-0.692019,7.99,15.2
1,P102,Bluetooth Speaker,1499,4.5,980,220,inf,-0.026924,-0.557310,14.99,9.8
2,P103,USB Keyboard,699,4.1,870,180,inf,-0.021636,-0.711263,6.99,8.7
3,P104,Gaming Headset,2499,4.6,2100,410,inf,-0.080773,-0.364869,24.99,21.0
4,P105,Smartwatch,3999,4.4,3050,520,inf,-0.126448,-0.076207,39.99,30.5
5,P106,Power Bank,1199,4.2,1750,390,inf,-0.063945,-0.615043,11.99,17.5
6,P107,Laptop Stand,899,4.0,620,140,inf,-0.009616,-0.672775,8.99,6.2
7,P108,Webcam,1899,4.3,1120,260,inf,-0.033655,-0.480334,18.99,11.2
8,P109,Portable SSD,5499,4.7,1850,330,inf,-0.068753,0.212455,54.99,18.5
9,P110,Wireless Charger,999,4.2,760,190,inf,-0.016347,-0.653531,9.99,7.6
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,inf,-0.181740,0.693559,79.99,42.0
11,P112,Mechanical Keyboard,4599,4.5,2100,290,inf,-0.080773,0.039258,45.99,21.0
12,P113,Gaming Mouse,1599,4.4,1300,340,inf,-0.042310,-0.538066,15.99,13.0
13,P114,Tablet Stand,699,4.1,540,120,inf,-0.005770,-0.711263,6.99,5.4
14,P115,USB Hub,899,4.2,870,200,inf,-0.021636,-0.672775,8.99,8.7
15,P116,External Hard Drive,6499,4.6,2300,310,inf,-0.090389,0.404897,64.99,23.0
16,P117,Smartphone Tripod,1199,4.3,760,210,inf,-0.016347,-0.615043,11.99,7.6
17,P118,Laptop Backpack,1999,4.4,1600,420,inf,-0.056733,-0.461090,19.99,16.0
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,inf,-0.148084,-0.268648,29.99,35.0
19,P120,LED Desk Lamp,1299,4.3,980,260,inf,-0.026924,-0.595799,12.99,9.8
20,P121,Phone Holder,499,4.0,420,150,inf,-0.000000,-0.749752,4.99,4.2
21,P122,Wireless Keyboard,2499,4.4,1450,310,inf,-0.049522,-0.364869,24.99,14.5
22,P123,Portable Monitor,8999,4.6,1250,170,inf,-0.039906,0.886000,89.99,12.5
23,P124,Smart Plug,799,4.2,720,210,inf,-0.014424,-0.692019,7.99,7.2
24,P125,WiFi Router,3499,4.5,2100,390,inf,-0.080773,-0.172428,34.99,21.0
25,P126,Graphics Tablet,4599,4.4,980,160,inf,-0.026924,0.039258,45.99,9.8
26,P127,VR Headset,12999,4.7,3100,140,inf,-0.128852,1.655766,129.99,31.0
27,P128,Microphone,2199,4.3,1300,270,inf,-0.042310,-0.422601,21.99,13.0
28,P129,Smart Light Bulb,699,4.2,880,240,inf,-0.022116,-0.711263,6.99,8.8
29,P130,Laptop Cooling Pad,1499,4.3,990,260,inf,-0.027405,-0.557310,14.99,9.9
30,P131,Action Camera,9999,4.6,2100,200,inf,-0.080773,1.078442,99.99,21.0
31,P132,Smart Doorbell,5999,4.5,1750,180,inf,-0.063945,0.308676,59.99,17.5
32,P133,Streaming Stick,3499,4.4,2500,430,inf,-0.100005,-0.172428,34.99,25.0
33,P134,Portable Projector,11999,4.6,1450,120,inf,-0.049522,1.463325,119.99,14.5
34,P135,Gaming Chair,15999,4.7,2100,90,inf,-0.080773,2.233090,159.99,21.0
35,P136,Desk Organizer,599,4.1,450,160,inf,-0.001442,-0.730508,5.99,4.5
36,P137,USB Flash Drive,799,4.2,900,320,inf,-0.023078,-0.692019,7.99,9.0
37,P138,Phone Screen Protector,299,4.0,600,380,NaN,-0.008654,-0.788240,2.99,6.0
38,P139,Laptop Sleeve,999,4.3,720,210,inf,-0.014424,-0.653531,9.99,7.2
39,P140,Wireless Presenter,1499,4.4,520,130,inf,-0.004808,-0.557310,14.99,5.2
40,P141,Tablet Keyboard Case,2999,4.5,850,150,inf,-0.020674,-0.268648,29.99,8.5
41,P142,Smart Thermostat,10999,4.6,1200,110,inf,-0.037502,1.270883,109.99,12.0
42,P143,Security Camera,4999,4.4,2100,260,inf,-0.080773,0.116235,49.99,21.0
43,P144,Drone Camera,24999,4.7,1800,70,inf,-0.066349,3.965063,249.99,18.0
44,P145,Electric Kettle,1999,4.3,1400,310,inf,-0.047118,-0.461090,19.99,14.0
45,P146,Air Fryer,7999,4.6,2200,200,inf,-0.085581,0.693559,79.99,22.0
46,P147,Robot Vacuum,18999,4.5,1650,120,inf,-0.059137,2.810415,189.99,16.5
47,P148,Smart Scale,2499,4.4,980,170,inf,-0.026924,-0.364869,24.99,9.8
48,P149,Digital Photo Frame,3499,4.3,870,150,inf,-0.021636,-0.172428,34.99,8.7
49,P150,Portable Fan,999,4.2,760,240,inf,-0.016347,-0.653531,9.99,7.6

In [27]:
df['Reviews_MinMax'] = (df['Reviews'] - df['Reviews'].min()) / (df['Reviews'].max()
- df['Price'].max())
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Reviews_MinMax,Price_ZScore,Price_Scaled,Review_Scaled
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,-0.052887,-0.692019,7.99,15.2
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,-0.026924,-0.557310,14.99,9.8
2,P103,USB Keyboard,699,4.1,870,180,0.016194,-0.021636,-0.711263,6.99,8.7
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,-0.080773,-0.364869,24.99,21.0
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,-0.126448,-0.076207,39.99,30.5
5,P106,Power Bank,1199,4.2,1750,390,0.036437,-0.063945,-0.615043,11.99,17.5
6,P107,Laptop Stand,899,4.0,620,140,0.024291,-0.009616,-0.672775,8.99,6.2
7,P108,Webcam,1899,4.3,1120,260,0.064777,-0.033655,-0.480334,18.99,11.2
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,-0.068753,0.212455,54.99,18.5
9,P110,Wireless Charger,999,4.2,760,190,0.028340,-0.016347,-0.653531,9.99,7.6
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,-0.181740,0.693559,79.99,42.0
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,-0.080773,0.039258,45.99,21.0
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,-0.042310,-0.538066,15.99,13.0
13,P114,Tablet Stand,699,4.1,540,120,0.016194,-0.005770,-0.711263,6.99,5.4
14,P115,USB Hub,899,4.2,870,200,0.024291,-0.021636,-0.672775,8.99,8.7
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,-0.090389,0.404897,64.99,23.0
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,-0.016347,-0.615043,11.99,7.6
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,-0.056733,-0.461090,19.99,16.0
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,-0.148084,-0.268648,29.99,35.0
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,-0.026924,-0.595799,12.99,9.8
20,P121,Phone Holder,499,4.0,420,150,0.008097,-0.000000,-0.749752,4.99,4.2
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,-0.049522,-0.364869,24.99,14.5
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,-0.039906,0.886000,89.99,12.5
23,P124,Smart Plug,799,4.2,720,210,0.020243,-0.014424,-0.692019,7.99,7.2
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,-0.080773,-0.172428,34.99,21.0
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,-0.026924,0.039258,45.99,9.8
26,P127,VR Headset,12999,4.7,3100,140,0.514170,-0.128852,1.655766,129.99,31.0
27,P128,Microphone,2199,4.3,1300,270,0.076923,-0.042310,-0.422601,21.99,13.0
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,-0.022116,-0.711263,6.99,8.8
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,-0.027405,-0.557310,14.99,9.9
30,P131,Action Camera,9999,4.6,2100,200,0.392713,-0.080773,1.078442,99.99,21.0
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,-0.063945,0.308676,59.99,17.5
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,-0.100005,-0.172428,34.99,25.0
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,-0.049522,1.463325,119.99,14.5
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,-0.080773,2.233090,159.99,21.0
35,P136,Desk Organizer,599,4.1,450,160,0.012146,-0.001442,-0.730508,5.99,4.5
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,-0.023078,-0.692019,7.99,9.0
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,-0.008654,-0.788240,2.99,6.0
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,-0.014424,-0.653531,9.99,7.2
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,-0.004808,-0.557310,14.99,5.2
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,-0.020674,-0.268648,29.99,8.5
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,-0.037502,1.270883,109.99,12.0
42,P143,Security Camera,4999,4.4,2100,260,0.190283,-0.080773,0.116235,49.99,21.0
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,-0.066349,3.965063,249.99,18.0
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,-0.047118,-0.461090,19.99,14.0
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,-0.085581,0.693559,79.99,22.0
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,-0.059137,2.810415,189.99,16.5
47,P148,Smart Scale,2499,4.4,980,170,0.089069,-0.026924,-0.364869,24.99,9.8
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,-0.021636,-0.172428,34.99,8.7
49,P150,Portable Fan,999,4.2,760,240,0.028340,-0.016347,-0.653531,9.99,7.6

In [22]:
df['Reviews_MinMax'] = (df['Reviews'] - df['Reviews'].min()) / (df['Reviews'].max()
- df['Price'].min())
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Reviews_MinMax
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,0.281979
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,0.143553
2,P103,USB Keyboard,699,4.1,870,180,0.016194,0.115355
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,0.430659
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,0.674186
5,P106,Power Bank,1199,4.2,1750,390,0.036437,0.340938
6,P107,Laptop Stand,899,4.0,620,140,0.024291,0.051269
7,P108,Webcam,1899,4.3,1120,260,0.064777,0.179441
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,0.366573
9,P110,Wireless Charger,999,4.2,760,190,0.028340,0.087157
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,0.968982
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,0.430659
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,0.225583
13,P114,Tablet Stand,699,4.1,540,120,0.016194,0.030761
14,P115,USB Hub,899,4.2,870,200,0.024291,0.115355
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,0.481928
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,0.087157
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,0.302487
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,0.789541
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,0.143553
20,P121,Phone Holder,499,4.0,420,150,0.008097,0.000000
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,0.264035
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,0.212766
23,P124,Smart Plug,799,4.2,720,210,0.020243,0.076903
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,0.430659
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,0.143553
26,P127,VR Headset,12999,4.7,3100,140,0.514170,0.687003
27,P128,Microphone,2199,4.3,1300,270,0.076923,0.225583
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,0.117918
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,0.146116
30,P131,Action Camera,9999,4.6,2100,200,0.392713,0.430659
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,0.340938
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,0.533197
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,0.264035
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,0.430659
35,P136,Desk Organizer,599,4.1,450,160,0.012146,0.007690
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,0.123045
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,0.046142
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,0.076903
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,0.025634
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,0.110228
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,0.199949
42,P143,Security Camera,4999,4.4,2100,260,0.190283,0.430659
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,0.353755
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,0.251218
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,0.456293
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,0.315304
47,P148,Smart Scale,2499,4.4,980,170,0.089069,0.143553
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,0.115355
49,P150,Portable Fan,999,4.2,760,240,0.028340,0.087157

In [23]:
# Z - Score Normalisation
df['Price_ZScore'] = (df['Price'] - df['Price'].mean()) / df['Price'].std()
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Reviews_MinMax,Price_ZScore
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,0.281979,-0.692019
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,0.143553,-0.557310
2,P103,USB Keyboard,699,4.1,870,180,0.016194,0.115355,-0.711263
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,0.430659,-0.364869
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,0.674186,-0.076207
5,P106,Power Bank,1199,4.2,1750,390,0.036437,0.340938,-0.615043
6,P107,Laptop Stand,899,4.0,620,140,0.024291,0.051269,-0.672775
7,P108,Webcam,1899,4.3,1120,260,0.064777,0.179441,-0.480334
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,0.366573,0.212455
9,P110,Wireless Charger,999,4.2,760,190,0.028340,0.087157,-0.653531
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,0.968982,0.693559
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,0.430659,0.039258
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,0.225583,-0.538066
13,P114,Tablet Stand,699,4.1,540,120,0.016194,0.030761,-0.711263
14,P115,USB Hub,899,4.2,870,200,0.024291,0.115355,-0.672775
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,0.481928,0.404897
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,0.087157,-0.615043
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,0.302487,-0.461090
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,0.789541,-0.268648
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,0.143553,-0.595799
20,P121,Phone Holder,499,4.0,420,150,0.008097,0.000000,-0.749752
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,0.264035,-0.364869
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,0.212766,0.886000
23,P124,Smart Plug,799,4.2,720,210,0.020243,0.076903,-0.692019
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,0.430659,-0.172428
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,0.143553,0.039258
26,P127,VR Headset,12999,4.7,3100,140,0.514170,0.687003,1.655766
27,P128,Microphone,2199,4.3,1300,270,0.076923,0.225583,-0.422601
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,0.117918,-0.711263
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,0.146116,-0.557310
30,P131,Action Camera,9999,4.6,2100,200,0.392713,0.430659,1.078442
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,0.340938,0.308676
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,0.533197,-0.172428
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,0.264035,1.463325
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,0.430659,2.233090
35,P136,Desk Organizer,599,4.1,450,160,0.012146,0.007690,-0.730508
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,0.123045,-0.692019
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,0.046142,-0.788240
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,0.076903,-0.653531
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,0.025634,-0.557310
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,0.110228,-0.268648
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,0.199949,1.270883
42,P143,Security Camera,4999,4.4,2100,260,0.190283,0.430659,0.116235
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,0.353755,3.965063
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,0.251218,-0.461090
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,0.456293,0.693559
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,0.315304,2.810415
47,P148,Smart Scale,2499,4.4,980,170,0.089069,0.143553,-0.364869
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,0.115355,-0.172428
49,P150,Portable Fan,999,4.2,760,240,0.028340,0.087157,-0.653531

In [30]:
df['Review_ZScore'] = (df['Reviews'] - df['Reviews'].mean()) / df['Reviews'].std()
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Reviews_MinMax,Price_ZScore,Price_Scaled,Review_Scaled,Review_ZScore
0,P101,Wireless Mouse,799,4.3,1520,350,inf,-0.052887,-0.692019,7.99,15.2,0.075943
1,P102,Bluetooth Speaker,1499,4.5,980,220,inf,-0.026924,-0.557310,14.99,9.8,-0.577069
2,P103,USB Keyboard,699,4.1,870,180,inf,-0.021636,-0.711263,6.99,8.7,-0.710090
3,P104,Gaming Headset,2499,4.6,2100,410,inf,-0.080773,-0.364869,24.99,21.0,0.777327
4,P105,Smartwatch,3999,4.4,3050,520,inf,-0.126448,-0.076207,39.99,30.5,1.926145
5,P106,Power Bank,1199,4.2,1750,390,inf,-0.063945,-0.615043,11.99,17.5,0.354078
6,P107,Laptop Stand,899,4.0,620,140,inf,-0.009616,-0.672775,8.99,6.2,-1.012411
7,P108,Webcam,1899,4.3,1120,260,inf,-0.033655,-0.480334,18.99,11.2,-0.407770
8,P109,Portable SSD,5499,4.7,1850,330,inf,-0.068753,0.212455,54.99,18.5,0.475006
9,P110,Wireless Charger,999,4.2,760,190,inf,-0.016347,-0.653531,9.99,7.6,-0.843111
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,inf,-0.181740,0.693559,79.99,42.0,3.316819
11,P112,Mechanical Keyboard,4599,4.5,2100,290,inf,-0.080773,0.039258,45.99,21.0,0.777327
12,P113,Gaming Mouse,1599,4.4,1300,340,inf,-0.042310,-0.538066,15.99,13.0,-0.190099
13,P114,Tablet Stand,699,4.1,540,120,inf,-0.005770,-0.711263,6.99,5.4,-1.109154
14,P115,USB Hub,899,4.2,870,200,inf,-0.021636,-0.672775,8.99,8.7,-0.710090
15,P116,External Hard Drive,6499,4.6,2300,310,inf,-0.090389,0.404897,64.99,23.0,1.019183
16,P117,Smartphone Tripod,1199,4.3,760,210,inf,-0.016347,-0.615043,11.99,7.6,-0.843111
17,P118,Laptop Backpack,1999,4.4,1600,420,inf,-0.056733,-0.461090,19.99,16.0,0.172685
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,inf,-0.148084,-0.268648,29.99,35.0,2.470321
19,P120,LED Desk Lamp,1299,4.3,980,260,inf,-0.026924,-0.595799,12.99,9.8,-0.577069
20,P121,Phone Holder,499,4.0,420,150,inf,-0.000000,-0.749752,4.99,4.2,-1.254267
21,P122,Wireless Keyboard,2499,4.4,1450,310,inf,-0.049522,-0.364869,24.99,14.5,-0.008707
22,P123,Portable Monitor,8999,4.6,1250,170,inf,-0.039906,0.886000,89.99,12.5,-0.250563
23,P124,Smart Plug,799,4.2,720,210,inf,-0.014424,-0.692019,7.99,7.2,-0.891483
24,P125,WiFi Router,3499,4.5,2100,390,inf,-0.080773,-0.172428,34.99,21.0,0.777327
25,P126,Graphics Tablet,4599,4.4,980,160,inf,-0.026924,0.039258,45.99,9.8,-0.577069
26,P127,VR Headset,12999,4.7,3100,140,inf,-0.128852,1.655766,129.99,31.0,1.986609
27,P128,Microphone,2199,4.3,1300,270,inf,-0.042310,-0.422601,21.99,13.0,-0.190099
28,P129,Smart Light Bulb,699,4.2,880,240,inf,-0.022116,-0.711263,6.99,8.8,-0.697998
29,P130,Laptop Cooling Pad,1499,4.3,990,260,inf,-0.027405,-0.557310,14.99,9.9,-0.564977
30,P131,Action Camera,9999,4.6,2100,200,inf,-0.080773,1.078442,99.99,21.0,0.777327
31,P132,Smart Doorbell,5999,4.5,1750,180,inf,-0.063945,0.308676,59.99,17.5,0.354078
32,P133,Streaming Stick,3499,4.4,2500,430,inf,-0.100005,-0.172428,34.99,25.0,1.261039
33,P134,Portable Projector,11999,4.6,1450,120,inf,-0.049522,1.463325,119.99,14.5,-0.008707
34,P135,Gaming Chair,15999,4.7,2100,90,inf,-0.080773,2.233090,159.99,21.0,0.777327
35,P136,Desk Organizer,599,4.1,450,160,inf,-0.001442,-0.730508,5.99,4.5,-1.217989
36,P137,USB Flash Drive,799,4.2,900,320,inf,-0.023078,-0.692019,7.99,9.0,-0.673812
37,P138,Phone Screen Protector,299,4.0,600,380,NaN,-0.008654,-0.788240,2.99,6.0,-1.036597
38,P139,Laptop Sleeve,999,4.3,720,210,inf,-0.014424,-0.653531,9.99,7.2,-0.891483
39,P140,Wireless Presenter,1499,4.4,520,130,inf,-0.004808,-0.557310,14.99,5.2,-1.133339
40,P141,Tablet Keyboard Case,2999,4.5,850,150,inf,-0.020674,-0.268648,29.99,8.5,-0.734276
41,P142,Smart Thermostat,10999,4.6,1200,110,inf,-0.037502,1.270883,109.99,12.0,-0.311027
42,P143,Security Camera,4999,4.4,2100,260,inf,-0.080773,0.116235,49.99,21.0,0.777327
43,P144,Drone Camera,24999,4.7,1800,70,inf,-0.066349,3.965063,249.99,18.0,0.414542
44,P145,Electric Kettle,1999,4.3,1400,310,inf,-0.047118,-0.461090,19.99,14.0,-0.069171
45,P146,Air Fryer,7999,4.6,2200,200,inf,-0.085581,0.693559,79.99,22.0,0.898255
46,P147,Robot Vacuum,18999,4.5,1650,120,inf,-0.059137,2.810415,189.99,16.5,0.233150
47,P148,Smart Scale,2499,4.4,980,170,inf,-0.026924,-0.364869,24.99,9.8,-0.577069
48,P149,Digital Photo Frame,3499,4.3,870,150,inf,-0.021636,-0.172428,34.99,8.7,-0.710090
49,P150,Portable Fan,999,4.2,760,240,inf,-0.016347,-0.653531,9.99,7.6,-0.843111

In [24]:
# Decimal Scaling
df['Price_Scaled'] = df['Price'] / 100
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Reviews_MinMax,Price_ZScore,Price_Scaled
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,0.281979,-0.692019,7.99
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,0.143553,-0.557310,14.99
2,P103,USB Keyboard,699,4.1,870,180,0.016194,0.115355,-0.711263,6.99
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,0.430659,-0.364869,24.99
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,0.674186,-0.076207,39.99
5,P106,Power Bank,1199,4.2,1750,390,0.036437,0.340938,-0.615043,11.99
6,P107,Laptop Stand,899,4.0,620,140,0.024291,0.051269,-0.672775,8.99
7,P108,Webcam,1899,4.3,1120,260,0.064777,0.179441,-0.480334,18.99
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,0.366573,0.212455,54.99
9,P110,Wireless Charger,999,4.2,760,190,0.028340,0.087157,-0.653531,9.99
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,0.968982,0.693559,79.99
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,0.430659,0.039258,45.99
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,0.225583,-0.538066,15.99
13,P114,Tablet Stand,699,4.1,540,120,0.016194,0.030761,-0.711263,6.99
14,P115,USB Hub,899,4.2,870,200,0.024291,0.115355,-0.672775,8.99
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,0.481928,0.404897,64.99
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,0.087157,-0.615043,11.99
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,0.302487,-0.461090,19.99
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,0.789541,-0.268648,29.99
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,0.143553,-0.595799,12.99
20,P121,Phone Holder,499,4.0,420,150,0.008097,0.000000,-0.749752,4.99
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,0.264035,-0.364869,24.99
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,0.212766,0.886000,89.99
23,P124,Smart Plug,799,4.2,720,210,0.020243,0.076903,-0.692019,7.99
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,0.430659,-0.172428,34.99
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,0.143553,0.039258,45.99
26,P127,VR Headset,12999,4.7,3100,140,0.514170,0.687003,1.655766,129.99
27,P128,Microphone,2199,4.3,1300,270,0.076923,0.225583,-0.422601,21.99
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,0.117918,-0.711263,6.99
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,0.146116,-0.557310,14.99
30,P131,Action Camera,9999,4.6,2100,200,0.392713,0.430659,1.078442,99.99
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,0.340938,0.308676,59.99
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,0.533197,-0.172428,34.99
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,0.264035,1.463325,119.99
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,0.430659,2.233090,159.99
35,P136,Desk Organizer,599,4.1,450,160,0.012146,0.007690,-0.730508,5.99
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,0.123045,-0.692019,7.99
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,0.046142,-0.788240,2.99
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,0.076903,-0.653531,9.99
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,0.025634,-0.557310,14.99
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,0.110228,-0.268648,29.99
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,0.199949,1.270883,109.99
42,P143,Security Camera,4999,4.4,2100,260,0.190283,0.430659,0.116235,49.99
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,0.353755,3.965063,249.99
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,0.251218,-0.461090,19.99
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,0.456293,0.693559,79.99
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,0.315304,2.810415,189.99
47,P148,Smart Scale,2499,4.4,980,170,0.089069,0.143553,-0.364869,24.99
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,0.115355,-0.172428,34.99
49,P150,Portable Fan,999,4.2,760,240,0.028340,0.087157,-0.653531,9.99

In [26]:
df['Review_Scaled'] = df['Reviews'] / 100
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Reviews_MinMax,Price_ZScore,Price_Scaled,Review_Scaled
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,0.281979,-0.692019,7.99,15.2
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,0.143553,-0.557310,14.99,9.8
2,P103,USB Keyboard,699,4.1,870,180,0.016194,0.115355,-0.711263,6.99,8.7
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,0.430659,-0.364869,24.99,21.0
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,0.674186,-0.076207,39.99,30.5
5,P106,Power Bank,1199,4.2,1750,390,0.036437,0.340938,-0.615043,11.99,17.5
6,P107,Laptop Stand,899,4.0,620,140,0.024291,0.051269,-0.672775,8.99,6.2
7,P108,Webcam,1899,4.3,1120,260,0.064777,0.179441,-0.480334,18.99,11.2
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,0.366573,0.212455,54.99,18.5
9,P110,Wireless Charger,999,4.2,760,190,0.028340,0.087157,-0.653531,9.99,7.6
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,0.968982,0.693559,79.99,42.0
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,0.430659,0.039258,45.99,21.0
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,0.225583,-0.538066,15.99,13.0
13,P114,Tablet Stand,699,4.1,540,120,0.016194,0.030761,-0.711263,6.99,5.4
14,P115,USB Hub,899,4.2,870,200,0.024291,0.115355,-0.672775,8.99,8.7
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,0.481928,0.404897,64.99,23.0
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,0.087157,-0.615043,11.99,7.6
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,0.302487,-0.461090,19.99,16.0
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,0.789541,-0.268648,29.99,35.0
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,0.143553,-0.595799,12.99,9.8
20,P121,Phone Holder,499,4.0,420,150,0.008097,0.000000,-0.749752,4.99,4.2
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,0.264035,-0.364869,24.99,14.5
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,0.212766,0.886000,89.99,12.5
23,P124,Smart Plug,799,4.2,720,210,0.020243,0.076903,-0.692019,7.99,7.2
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,0.430659,-0.172428,34.99,21.0
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,0.143553,0.039258,45.99,9.8
26,P127,VR Headset,12999,4.7,3100,140,0.514170,0.687003,1.655766,129.99,31.0
27,P128,Microphone,2199,4.3,1300,270,0.076923,0.225583,-0.422601,21.99,13.0
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,0.117918,-0.711263,6.99,8.8
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,0.146116,-0.557310,14.99,9.9
30,P131,Action Camera,9999,4.6,2100,200,0.392713,0.430659,1.078442,99.99,21.0
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,0.340938,0.308676,59.99,17.5
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,0.533197,-0.172428,34.99,25.0
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,0.264035,1.463325,119.99,14.5
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,0.430659,2.233090,159.99,21.0
35,P136,Desk Organizer,599,4.1,450,160,0.012146,0.007690,-0.730508,5.99,4.5
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,0.123045,-0.692019,7.99,9.0
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,0.046142,-0.788240,2.99,6.0
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,0.076903,-0.653531,9.99,7.2
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,0.025634,-0.557310,14.99,5.2
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,0.110228,-0.268648,29.99,8.5
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,0.199949,1.270883,109.99,12.0
42,P143,Security Camera,4999,4.4,2100,260,0.190283,0.430659,0.116235,49.99,21.0
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,0.353755,3.965063,249.99,18.0
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,0.251218,-0.461090,19.99,14.0
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,0.456293,0.693559,79.99,22.0
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,0.315304,2.810415,189.99,16.5
47,P148,Smart Scale,2499,4.4,980,170,0.089069,0.143553,-0.364869,24.99,9.8
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,0.115355,-0.172428,34.99,8.7
49,P150,Portable Fan,999,4.2,760,240,0.028340,0.087157,-0.653531,9.99,7.6

In [40]:
# Turning categorical variables into quantative variables
df = pd.read_csv('/content/Student-Dataset.csv')
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [44]:
# Label Encoding - Placement Status
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Placement_Label'] = le.fit_transform(df['Placement_Status'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,1
1,102,Male,IT,7.5,1,85,Not Placed,0,0
2,103,Female,ENTC,9.1,0,96,Placed,550000,1
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,0
4,105,Female,Computer,8.7,0,88,Placed,480000,1
5,106,Male,Civil,7.2,3,72,Not Placed,0,0
6,107,Female,IT,8.9,0,91,Placed,500000,1
7,108,Male,Computer,6.5,1,80,Not Placed,0,0
8,109,Female,ENTC,7.8,0,84,Placed,420000,1
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,0

In [47]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Attendance_Placement_Label'] = le.fit_transform(df['Attendance_Percentage'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Attendance_Placement_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,1,8
1,102,Male,IT,7.5,1,85,Not Placed,0,0,5
2,103,Female,ENTC,9.1,0,96,Placed,550000,1,9
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,0,2
4,105,Female,Computer,8.7,0,88,Placed,480000,1,6
5,106,Male,Civil,7.2,3,72,Not Placed,0,0,0
6,107,Female,IT,8.9,0,91,Placed,500000,1,7
7,108,Male,Computer,6.5,1,80,Not Placed,0,0,3
8,109,Female,ENTC,7.8,0,84,Placed,420000,1,4
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,0,1

In [48]:
# One Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Placement_Status'])
df_encoded

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Salary,Placement_Label,Attendance_Placement_Label,Placement_Status_Not Placed,Placement_Status_Placed
0,101,Female,Computer,8.2,0,92,450000,1,8,False,True
1,102,Male,IT,7.5,1,85,0,0,5,True,False
2,103,Female,ENTC,9.1,0,96,550000,1,9,False,True
3,104,Male,Mechanical,6.8,2,78,0,0,2,True,False
4,105,Female,Computer,8.7,0,88,480000,1,6,False,True
5,106,Male,Civil,7.2,3,72,0,0,0,True,False
6,107,Female,IT,8.9,0,91,500000,1,7,False,True
7,108,Male,Computer,6.5,1,80,0,0,3,True,False
8,109,Female,ENTC,7.8,0,84,420000,1,4,False,True
9,110,Male,Mechanical,7.0,2,76,0,0,1,True,False

In [49]:
df_encoded = pd.get_dummies(df, columns=['Gender'])
df_encoded

,Roll_No,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Attendance_Placement_Label,Gender_Female,Gender_Male
0,101,Computer,8.2,0,92,Placed,450000,1,8,True,False
1,102,IT,7.5,1,85,Not Placed,0,0,5,False,True
2,103,ENTC,9.1,0,96,Placed,550000,1,9,True,False
3,104,Mechanical,6.8,2,78,Not Placed,0,0,2,False,True
4,105,Computer,8.7,0,88,Placed,480000,1,6,True,False
5,106,Civil,7.2,3,72,Not Placed,0,0,0,False,True
6,107,IT,8.9,0,91,Placed,500000,1,7,True,False
7,108,Computer,6.5,1,80,Not Placed,0,0,3,False,True
8,109,ENTC,7.8,0,84,Placed,420000,1,4,True,False
9,110,Mechanical,7.0,2,76,Not Placed,0,0,1,False,True

In [52]:
# Dummy Encoding
df_dummy = pd.get_dummies(df1, columns=['Customer_Gender'], drop_first=True)
df_dummy

,Order ID,Payment_Method,Product-category,City,Order_value,Gender_Label,Customer_Gender_Male
0,101,Credit Card,Electronics,New York,1500,1,True
1,102,PayPal,Clothing,Los Angeles,800,0,False
2,103,Credit Card,Electronics,Chicago,2000,1,True
3,104,PayPal,Clothing,San Francisco,1667,0,False
4,105,Credit Card,Electronics,Miami,12788,1,True
5,106,PayPal,Clothing,Seattle,7756,0,False

In [53]:

df_dummy = pd.get_dummies(df1, columns=['Gender_Label'], drop_first=True)
df_dummy

,Order ID,Customer_Gender,Payment_Method,Product-category,City,Order_value,Gender_Label_1
0,101,Male,Credit Card,Electronics,New York,1500,True
1,102,Female,PayPal,Clothing,Los Angeles,800,False
2,103,Male,Credit Card,Electronics,Chicago,2000,True
3,104,Female,PayPal,Clothing,San Francisco,1667,False
4,105,Male,Credit Card,Electronics,Miami,12788,True
5,106,Female,PayPal,Clothing,Seattle,7756,False